-- 코드를 입력하세요
SELECT o.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT * p.PRICE) AS TOTAL_SALES FROM FOOD_ORDER o
INNER JOIN FOOD_PRODUCT p ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE o.PRODUCE_DATE LIKE '2022-05%'
GROUP BY o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, o.PRODUCT_ID ASC;